version: '3.1'

services:
     app:
          build:
               context: .
               dockerfile: ./Dockerfile
          container_name: app-container
          env_file:
               - ./.env
          ports:
               - 5000:5000
          command: npm start
          depends_on:
               - mysql

     mysql:
          image: mysql:8.0.28
          container_name : mysql-container
          command: --default-authentication-plugin=mysql_native_password
          restart: always
          ports: 
          - 3307:3306
          environment:
               MYSQL_ROOT_PASSWORD : root
               MYSQL_DATABASE : livraison_resto

