version: '3.4'

services:
 app:
    image: app
    build:
         context: .
         dockerfile: ./Dockerfile
    environment:
         NODE_ENV: production
    ports: 
      - 5000:5000   
 mysql:
    image: mysql
    container_name : mysql-container
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports: 3307:3306
    environment:
          MYSQL_ROOT_PASSWORD : root
          MYSQL_DATABASE : livraison resto   